name: Build Alfred Workflow

on:
  push:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Alfred Workflow
    	id: alfred_builder
      uses: mperezi/build-alfred-workflow@v1
      with:
        workflow_dir: src
        exclude_patterns: '*.pyc *__pycache__/*'